### ISSUE TITLE
Support node in a subdirectory of git repo

### ISSUE THREAD

**Issue by mblakele** [tarmolov/git-hooks-js#3]
This looks like a promising package, but I ran into a problem getting started. I have a repo where node lives at `www/node`. When I add git-hooks to `www/node/package.json` it installs successfully, but the hooks can't find node.

```
$ .git/hooks/pre-commit
Cannot find git-hooks. Did you install it?
``` 

I think this is similar to https://github.com/observing/pre-commit/issues/27 — and as noted there it gets more complex if there's more than one copy of node in the repo. For example I might have `admin/node` along with `www/node`, and I want git-hooks to run for both, each with its own separate `.githooks` directories.

**Comment by tarmolov** [comment]
Now `git-hooks` expects  `.githooks` directory on the same level as the closest `.git` directory.

Here is the project structure.
```
.git
.githooks/ (1)
admin/
  node/
    .githooks/ (2)
www/
   node/
     .githooks/ (3)
```
It's one git repo and `.git/hooks` is common for the whole project. 

What happen if I commit to `admin/node` directory? 1 and 2 should be executed but not 3? 
How should it work in your opinion?

**Comment by mblakele** [comment]
Yes, that's what I had in mind.

But I think it'd also be ok if you declared that only the root `.githooks` will work, and it's up to the user to write subdirectory behavior into the local hooks. The big problem is the `Cannot find git-hooks` message.

**Comment by tarmolov** [comment]
That's because nodejs [looks for a module up to the filesystem root](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders). `git-hooks` needs a some kind of hint to find `node_modules` hided deep inside :)

There are possible options:
  1.  Hardcode path to `git-hooks` during `git-hooks` installation. So if you install `git-hooks` in `admin/node` and `www/node` in consecutive way, `.git/hooks/pre-commit`will refer to `www/node/node_modules/git-hooks`.
  2.  Add config `.githooks.json` to the project root with path to `git-hooks`.
```json
{
    "gitHooksPath": "admin/node/node_modules/git-hooks"
}
```

I love `zero config` paradigm for simple utilities; so, I vote for option # 1. What do you think?

**Comment by mblakele** [comment]
Option (1) sounds workable if the order is deterministic. I wouldn't want to randomly get `www/node/node_modules/git-hooks` or `admin/node/node_modules/git-hooks` every time I run `npm install`.

Also it'd be great to have an optional `--path` option to `git-hooks --install`, to override the location of the `git-hooks` directory.

**Comment by tarmolov** [comment]
Check it out!
git-hooks@1.0.0-rc.2

**Comment by mblakele** [comment]
Thanks, this looks good. I got in working with `.githooks` in my repo root, which is ideal for my project. Feel free to close this whenever you're happy.
